language: node_js
node_js:
  - "0.12"

before_install:
  # Install Google Chrome
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - sudo chmod 1777 /dev/shm

  # Start xvfb
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
