language: node_js
node_js:
  - "4"
  - "5"

env:
  CXX=g++-4.8

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update

  - sudo apt-get install g++-4.8
  - sudo apt-get install google-chrome-stable
  - sudo apt-get install chromium-browser

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

test:
  - node --version
  - npm --version
  - npm test
